name: PALOXIS-HUB-AUTOMATION
on:
  schedule:
    - cron: '0 12,20 * * *'
  workflow_dispatch:

jobs:
  run-hunter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install requests

      - name: Esecuzione Cacciatore
        run: python hunter.py
