name: PALOXIS-HUB-AUTOMATION
on:
  schedule:
    - cron: '*/15 * * * *'  # Gira automaticamente ogni 15 minuti, h24
  workflow_dispatch:        # Ti permette di avviarlo tu quando vuoi premendo il tasto

jobs:
  run-hunter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install requests

      - name: Esecuzione Cacciatore
        run: python hunter/hunter.py
